package com.z7design.fleet_manager.model.enums;

public enum UserGroup {
    GRUPO_SUPER_ADMIN,
    GRUPO_ADMIN,
    GRUPO_GESTOR,
    GRUPO_RH,
    GRUPO_DPE,
    GRUPO_SUPERVISOR,
    GRUPO_COLABORADORES,
    GRUPO_OPERACIONAL,
    GRUPO_VIGILANTES,
    GRUPO_FINANCEIRO,
    GRUPO_TI_SUPORTE,
    GRUPO_AUDITOR,
    GRUPO_AUXILIARES
} 
