# ===================== CONFIGURAÇÃO PARA VPS - CI/CD =====================

# ===================== CONFIGURAÇÃO DE BANCO DE DADOS =====================
spring.datasource.url=jdbc:postgresql://localhost:5432/secured_guard_ci
spring.datasource.username=postgressg
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================== CONFIGURAÇÃO JPA VPS CI =====================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===================== CONFIGURAÇÃO FLYWAY =====================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false
spring.flyway.out-of-order=true
spring.flyway.validate-on-migrate=false
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.ignore-migration-patterns=*:missing,*:future,*:pending

# ===================== CONFIGURAÇÃO DE LOGGING =====================
logging.level.root=WARN
logging.level.com.z7design.secured_guard=INFO

# ===================== CONFIGURAÇÃO DE SERVIDOR =====================
server.port=8081

# ===================== CONFIGURAÇÃO JWT =====================
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:604800000}
jwt.header=Authorization
jwt.prefix=Bearer
jwt.refreshTokenExpiration=${JWT_REFRESH_EXPIRATION:604800000}

# ===================== CONFIGURAÇÃO DE EMAIL PARA CI =====================
spring.mail.host=${MAIL_HOST:186.209.113.105}
spring.mail.port=${MAIL_PORT:465}
spring.mail.username=${MAIL_USERNAME:securedguard@z7design.com.br}
spring.mail.password=${MAIL_PASSWORD:D8rKeqSFZfaS$(y7}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS_REQUIRED:false}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SSL_ENABLE:true}

# ===================== CONFIGURAÇÃO DE SINCRONIZAÇÃO =====================
app.database.sync.enabled=false
app.database.sync.interval=300000
