# Flyway Configuration for secured_guard_test
flyway.url=jdbc:postgresql://localhost:5432/secured_guard_test
flyway.user=postgres
flyway.password=1234567
flyway.locations=filesystem:src/main/resources/db/migration
flyway.baselineOnMigrate=true
flyway.baselineVersion=1
flyway.outOfOrder=true
flyway.validateOnMigrate=false
flyway.cleanDisabled=false

