// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdianxdevkweflkjkusn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkaWFueGRldmt3ZWZsa2prdXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTQ2NjksImV4cCI6MjA2MjE5MDY2OX0.yQUZMieMxNEk_F5PMB8wN5DmECO1c2V2b-YdO0KMSNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);