-- Inserir dados de teste na tabela user_activity_logs
INSERT INTO user_activity_logs (
    id, 
    user_id, 
    username, 
    action, 
    module, 
    details, 
    ip_address, 
    user_agent, 
    session_id, 
    status, 
    execution_time_ms, 
    created_at, 
    ended_at
) VALUES 
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'LOGIN',
    'AUTENTICACAO',
    'POST /api/auth/login - Login realizado com sucesso',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    150,
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '2 hours' + INTERVAL '150 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'CONSULTAR',
    'USUARIOS',
    'GET /api/users - Listagem de usuários',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    200,
    NOW() - INTERVAL '1 hour 30 minutes',
    NOW() - INTERVAL '1 hour 30 minutes' + INTERVAL '200 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'CRIAR',
    'FUNCIONARIOS',
    'POST /api/employees - Criação de funcionário João Silva',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    300,
    NOW() - INTERVAL '1 hour',
    NOW() - INTERVAL '1 hour' + INTERVAL '300 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'ATUALIZAR',
    'VEICULOS',
    'PUT /api/vehicles/123 - Atualização de veículo ABC-1234',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    250,
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '45 minutes' + INTERVAL '250 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'EXCLUIR',
    'ESTOQUE',
    'DELETE /api/inventory/456 - Exclusão de item do estoque',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'ERROR',
    100,
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '30 minutes' + INTERVAL '100 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'CONSULTAR',
    'LOGS_ATIVIDADE',
    'GET /api/activity-logs - Consulta de logs de atividade',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    180,
    NOW() - INTERVAL '15 minutes',
    NOW() - INTERVAL '15 minutes' + INTERVAL '180 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'EXPORTAR',
    'RELATORIOS',
    'GET /api/reports/export - Exportação de relatório financeiro',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    500,
    NOW() - INTERVAL '10 minutes',
    NOW() - INTERVAL '10 minutes' + INTERVAL '500 milliseconds'
),
(
    gen_random_uuid(),
    (SELECT id FROM users WHERE username = 'superadmin' LIMIT 1),
    'superadmin',
    'ATUALIZAR',
    'PERMISSOES',
    'PUT /api/roles/123 - Atualização de permissões do usuário',
    '192.168.1.100',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'session_' || gen_random_uuid(),
    'SUCCESS',
    220,
    NOW() - INTERVAL '5 minutes',
    NOW() - INTERVAL '5 minutes' + INTERVAL '220 milliseconds'
);
